[RV32I]

################################################################################
#    INSTRUCTION FIELDS 
################################################################################

[RV32I.FIELDS]
# Definitions according to decode_field module

[RV32I.FIELDS.opcode]
token     = 0
subfields = [{ bits = 7,  offset =  0 }]

[RV32I.FIELDS.funct3]
token     = 0
subfields = [{ bits = 3,  offset = 12 }]

[RV32I.FIELDS.funct7]
token = 0
subfields = [{ bits = 7,  offset = 25 }]

[RV32I.FIELDS.rs1]
token = { "ITYPE" = 2, "RTYPE" = 3 }
subfields = [{ bits = 5,  offset = 15 }]

[RV32I.FIELDS.rs2]
token = { "RTYPE" = 2 } 
subfields = [{ bits = 5,  offset = 20 }]

[RV32I.FIELDS.rd]
token = 1 
subfields = [{ bits = 5,  offset =  7 }]

[RV32I.FIELDS.immediate12_itype]
token = 3 
subfields = [{ bits = 12, offset = 20 }]

[RV32I.FIELDS.immediate12_stype]
token = 3 
subfields = [{ bits = 7,  offset = 25 },
             { bits = 5,  offset =  7 }]

[RV32I.FIELDS.immediate12_btype]
token = 3 
subfields = [{ bits = 1,  offset = 31 },
             { bits = 1,  offset =  7 },
             { bits = 6,  offset = 25 },
             { bits = 4,  offset =  8 }]

[RV32I.FIELDS.immediate20_utype]
token = 3 
subfields = [{ bits = 20, offset = 20 }]

[RV32I.FIELDS.immediate20_jtype]
token = 3 
subfields = [{ bits = 1,  offset = 20 },
             { bits = 8,  offset = 12 },
             { bits = 1,  offset = 20 },
             { bits = 10, offset = 21 }]

################################################################################
#    INSTRUCTION DESCRIPTION
################################################################################

[RV32I.TYPE.RTYPE]
[RV32I.TYPE.RTYPE.INSTRUCTIONS]
RTYPE_BASE = [ "add","sll","slt","sltu","xor","srl","or","and" ]
RTYPE_EXTRA = [ "sub", "sra" ]
[RV32I.TYPE.RTYPE.OVERRIDES]
RTYPE_BASE  = { opcode = 0x33, funct7 = 0 }
RTYPE_EXTRA = { opcode = 0x33, funct7 = 32 }
[RV32I.TYPE.RTYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode","funct3", "funct7", "rs1", "rs2", "rd" ] 

[RV32I.TYPE.ITYPE]
[RV32I.TYPE.ITYPE.INSTRUCTIONS]
ITYPE     = [ "addi", "slti", "sltiu", "xori", "ori", "andi" ]
ITYPE_J   = [ "jalr" ] 
[RV32I.TYPE.ITYPE.OVERRIDES]
ITYPE     = { opcode = 0x13 }
ITYPE_J   = { opcode = 0x17 }
[RV32I.TYPE.ITYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode", "funct3", "rs1", "rd", "immediate12_itype" ] 

[RV32I.TYPE.STYPE]
[RV32I.TYPE.STYPE.INSTRUCTIONS]
STYPE = [ "tmps" ]
[RV32I.TYPE.STYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode", "funct3", "rs1", "rd", "immediate12_stype" ]

[RV32I.TYPE.BTYPE]
[RV32I.TYPE.BTYPE.INSTRUCTIONS]
BTYPE = [ "tmpb" ]
[RV32I.TYPE.BTYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode", "funct3", "rs1", "rd", "immediate12_btype" ]

[RV32I.TYPE.UTYPE]
[RV32I.TYPE.UTYPE.INSTRUCTIONS]
UTYPE = [ "tmpu" ]
[RV32I.TYPE.UTYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode", "funct3", "rs1", "rd", "immediate12_utype" ]

[RV32I.TYPE.JTYPE]
[RV32I.TYPE.JTYPE.INSTRUCTIONS]
JTYPE    = [ "jal" ] 
[RV32I.TYPE.JTYPE.INSTRUCTION_FIELDS]
fields    = [ "opcode", "funct3", "rs1", "rd", "immediate20_jtype" ]

